name: Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      
name: checkout
      uses: actions/checkout@v3
name: build
    run: |
      docker build . -t eliteszn/schoology:latest
name: publish
  run: |
    docker login -u eliteszn -p dckr_pat_4hPSHwydWKsgHyOPc61Fe11AKws
    docker push eliteszn/schoology:latest
